spring.application.name=ecom-application
spring.data.mongodb.uri=mongodb://localhost:27017/ecom_db
# Show MongoDB queries (equivalent to show-sql=true)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Log all MongoDB operations at wire level
logging.level.org.mongodb.driver.protocol.command=DEBUG
logging.level.org.springframework=DEBUG